#!/bin/sh
# expected_release="5.6"
expected_platform="i386"

release=`uname -r`
platform=`uname -p`

if [ ${platform} != ${expected_platform} ]; then
    echo "\n\n\n\tThis package must be installed on a ${expected_platform} architecture\n"
    echo "\tAborting installation.\n\n\n"
    exit 1
fi
#if [ ${release} != ${expected_release} ]; then
#    echo "\n\n\n\tThis package must be installed on a ${expected_release} machine\n"
#    echo "\tAborting installation.\n\n\n"
#    exit 1
#fi

exit 0
